# The Docker image that will be used to build your app
image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

before_script:
  - npm install -g @quasar/cli

build:
  stage: build
  script:
    - npm install
    - quasar build

deploy_production:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/spa/* .public
    - cp .htaccess .public
    - cp dist/spa/index.html .public/404.html
    - mv .public public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    # Add deployment commands for production environment
  artifacts:
    paths:
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH