image: node:16.13.0
cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

before_script:
  - npm install -g @quasar/cli

build:
  stage: build
  script:
    - npm install
    - quasar build

deploy_production:
  stage: deploy
  script:
    - npm install
    - quasar build
    - mkdir -p public
    - cp -r --remove-destination dist/spa/. public/
/bin/bash: line 138: rsync: command not found
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH