# The Docker image that will be used to build your app
image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

before_script:
  - npm install -g @quasar/cli

build:
  stage: build
  script:
    - npm install
    - quasar build

deploy_production:
  stage: deploy
  script:
    - npm install
    - quasar build
    - mv dist/spa public
    # Add deployment commands for production environment
  artifacts:
    paths:
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH