image: node:16.13.0
cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

before_script:
  - npm install -g @quasar/cli

build:
  stage: build
  script:
    - npm install
    - quasar build

deploy_production:
  stage: deploy
  script:
    - npm install
    - quasar build
    - mkdir -p public
    - rsync -av --delete dist/spa/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH